-- -- insert 1 row into the table
-- INSERT INTO
--     employees
-- VALUES (
--         1,
--         'Trời Thu',
--         'Mát Mẻ',
--         11.09,
--         '1997-09-11'
--     );

-- SELECT * FROM employees;

-- -- insert multiple rows into the table
-- INSERT INTO
--     employees
-- VALUES (
--         2,
--         'Phong Lan',
--         'Chi Chủ',
--         10.08,
--         '1997-08-10'
--     ),
--     (
--         3,
--         'Bên Dưới',
--         'Thâm Uyên',
--         333.3,
--         '2022-03-15'
--     ),
--     (
--         4,
--         'Thiên Hà',
--         'Lãng Khách',
--         444.4,
--         '2022-03-15'
--     ),
--     (
--         5,
--         'Hồn',
--         'Đế',
--         777.7,
--         '2018-09-20'
--     ),
--     (
--         6,
--         'Thiên',
--         'Mệnh',
--         999.9,
--         '2026-04-04'
--     );

-- SELECT * FROM employees;

-- -- insert a row with missing data
-- INSERT INTO
--     employees (
--         employee_id,
--         first_name,
--         last_name
--     )
-- VALUES (7, 'Zen', 'Tom');

-- SELECT * FROM employees;